# config/_default/menus.es.toml

[[main]]
  name = "Inicio"
  url = "/"
  weight = 1

[[main]]
  name = "Sobre mí"
  url = "/about/"
  weight = 2

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 3

[[main]]
  name = "CV"
  url = "/CV/"
  weight = 4

[[main]]
  name = "Contacto"
  url = "/contact/"
  weight = 5

[[main]]
  name = "GitHub"
  url = "https://github.com/jpanther/congo"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"