# config/_default/menus.es.toml

[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Sobre mí"
  url = "/about/"
  weight = 2

[[main]]
  name = "Blog"
  url = "https://blog.rbnetto.dev"
  weight = 6
  [main.params]
    icon = "medium"
    showName = false
    target = "_blank"

[[main]]
  name = "Contacto"
  url = "/contact/"
  weight = 5

[[main]]
  name = "GitHub"
  url = "https://github.com/Piuliss"
  weight = 6
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "Buscar"
  weight = 7
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"